---
downloads: ~/.ansible-downloads/

configure_dotfiles: true
configure_terminal: true
configure_osx: true

configure_sudoers: false
sudoers_custom_config: ''
# Example:
# sudoers_custom_config: |
#   # Allow users in admin group to use sudo with no password.
#   %admin ALL=(ALL) NOPASSWD: ALL

dotfiles_repo: https://github.com/trahma/dotfiles.git
dotfiles_repo_accept_hostkey: true
dotfiles_repo_local_destination: ~/Development/GitHub/dotfiles
dotfiles_files:
  - .gitignore
  - .inputrc
  - .osx
  - .tmux.conf
  - .vimrc

homebrew_installed_packages:
  # - ansible # Installed via Pip.
  - ack
  - autoconf
  - aws-shell
  - brew-pip
  - coreutils
  - doctl
  - ffmpeg
  - fish
  - fx
  - git
  - gnupg
  - grep
  - imagemagick
  - jq
  - magic-wormhole
  - mcrypt
  - memcached
  - mysql
  - nmap
  - node
  - nvm
  - p7zip
  - php@8.0
  - pv
  - recode
  - ssh-copy-id
  - telnet
  - tmuxinator
  - tree
  - watch
  - wget

homebrew_taps:
  - homebrew/core
  - homebrew/cask
  - homebrew/cask_versions
  - homebrew/cask_drivers

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - alfred
  - charles
  - discord
  - dropbox
  - firefox
  - fission
  - google-chrome
  - handbrake
  - logitech-options
  - loopback
  - iterm2
  - notion
  - qbittorrent
  - slack
  - signal
  - spotify
  - sublime-text
  - tweetbot
  - visual-studio-code-insiders
  - vlc
  - zoomus

# See `trahma.mas` role documentation for usage instructions.
mas_installed_apps:
  - { id: 425264550, name: "Blackmagic Disk Speed Test" }
  - { id: 411643860, name: "DaisyDisk" }
  - { id: 1518036000, name: "Sequel Ace"}
  - { id: 497799835, name: "Xcode" }
  - { id: 441258766, name: "Magnet" }
  - { id: 1289583905, name: "Pixelmator Pro"}
  - { id: 9449079, name: "Patterns - The Regex App"}
  - { id: 1295203466, name: "Microsoft Remote Desktop"}
  - { id: 1116599239, name: "NordVPN IKE - Unlimited VPN"}
  - { id: 421879749, name: "Rested - Simple HTTP Requests"}

mas_email: ""
mas_password: ""

osx_script: "~/.osx --no-restart"

# Install packages from other package managers.
# Note: You are responsible for making sure the required package managers are
# installed, eg. through homebrew.
composer_packages: []
# - name: drush
#   state: present # present/absent, default: present
#   version: "^8.1" # default: N/A
gem_packages: []
# - name: bundler
#   state: present # present/absent/latest, default: present
#   version: "~> 1.15.1" # default: N/A
npm_packages: []
# - name: webpack
#   state: present # present/absent/latest, default: present
#   version: "^2.6" # default: N/A
pip_packages: []
# - name: mkdocs
#   state: present # present/absent/latest, default: present
#   version: "0.16.3" # default: N/A

# Glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks: []
